[project]
name = "googlesearch"
version = "0.1.0"
description = "googlesearch with fake-useragent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "beautifulsoup4>=4.9",
  "fake-useragent>=2.0.3",
  "requests>=2.20"
]
